//DELIMITER
CREATE PROCEDURE TREFR_ACCEPT_CRIT()
BEGIN


DROP TABLE IF EXISTS TEMP_TABLE_TEST;

Create table TEMP_TABLE_TEST select * FROM MIGRATE_TEST;

ALTER TABLE TEMP_TABLE_TEST ADD EFFECTIVEDATE VARCHAR(255) AFTER VEHCAT;
ALTER TABLE TEMP_TABLE_TEST ADD CHANGETIMESTAMP VARCHAR(255) AFTER EFFECTIVEDATE ;
ALTER TABLE TEMP_TABLE_TEST ADD EFFECTIVEENDDATE VARCHAR(255) AFTER CHANGETIMESTAMP;
ALTER TABLE TEMP_TABLE_TEST ADD ENDDATETIMESTAMP VARCHAR(255) AFTER EFFECTIVEENDDATE;

UPDATE TEMP_TABLE_TEST 
SET 
    EFFECTIVEDATE = CONCAT(DATE_FORMAT((DATE_SUB(CURDATE(), INTERVAL 24 MONTH)),
                    '%Y%m'),
            '01');
UPDATE TEMP_TABLE_TEST 
SET 
    CHANGETIMESTAMP = CONCAT(DATE_FORMAT((DATE_SUB(CURDATE(), INTERVAL 24 MONTH)),
                    '%Y%m'),
            '01000000');

UPDATE TEMP_TABLE_TEST 
SET 
    EFFECTIVEENDDATE = '99991231';
UPDATE TEMP_TABLE_TEST 
SET 
    ENDDATETIMESTAMP = '99991231000000';

DROP TABLE IF EXISTS TEMP_TABLE_TEST_CRIT_1;

CREATE TABLE TEMP_TABLE_TEST_CRIT_1 AS SELECT * FROM
    TEMP_TABLE_TEST
WHERE
    VEHCAT = 'GU';

DROP TABLE IF EXISTS CRIT_GU;

CREATE TABLE CRIT_GU AS SELECT NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'AAMI' AS COMPANY,
    AAMACPT AS ACCEPTCRIT,
    AAMRULE AS INTERNETJEP FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    AAMACPT IS NOT NULL
        AND AAMRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'APIA' AS COMPANY,
    APIACPT AS ACCEPTCRIT,
    APIRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    APIACPT IS NOT NULL
        AND APIRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'SUNCORP' AS COMPANY,
    SUNACPT AS ACCEPTCRIT,
    SUNRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    SUNACPT IS NOT NULL
        AND SUNRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'VERO3' AS COMPANY,
    V03ACPT AS ACCEPTCRIT,
    V03RULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    V03ACPT IS NOT NULL
        AND V03RULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'VERO5' AS COMPANY,
    V05ACPT AS ACCEPTCRIT,
    V05RULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    V05ACPT IS NOT NULL
        AND V05RULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'GIO' AS COMPANY,
    GIOACPT AS ACCEPTCRIT,
    GIORULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    GIOACPT IS NOT NULL
        AND GIORULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'ESSENTIALS' AS COMPANY,
    ESSACPT AS ACCEPTCRIT,
    ESSRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    ESSACPT IS NOT NULL
        AND ESSRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'BINGLE' AS COMPANY,
    BINGLEACPT AS ACCEPTCRIT,
    BINGLERULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    BINGLEACPT IS NOT NULL
        AND BINGLERULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'GIOCI' AS COMPANY,
    GIOCIACPT AS ACCEPTCRIT,
    GIOCIRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    GIOCIACPT IS NOT NULL
        AND GIOCIRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'JCI' AS COMPANY,
    JCIACPT AS ACCEPTCRIT,
    JCIRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    JCIACPT IS NOT NULL
        AND JCIRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'SHANNONS' AS COMPANY,
    SHNACPT AS ACCEPTCRIT,
    SHNRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    SHNACPT IS NOT NULL
        AND SHNRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'AMP' AS COMPANY,
    AMPACPT AS ACCEPTCRIT,
    AMPRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_1
WHERE
    AMPACPT IS NOT NULL
        AND AMPRULE IS NOT NULL;

DROP TABLE IF EXISTS TEMP_TABLE_TEST_CRIT_2;

CREATE TABLE TEMP_TABLE_TEST_CRIT_2 AS SELECT * FROM
    TEMP_TABLE_TEST
WHERE
    VEHCAT = 'CI';


DROP TABLE IF EXISTS CRIT_CI;

CREATE TABLE CRIT_CI AS SELECT NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'GIOCI' AS COMPANY,
    GIOCIACPT AS ACCEPTCRIT,
    GIOCIRULE AS INTERNETJEP FROM
    TEMP_TABLE_TEST_CRIT_2
WHERE
    GIOCIACPT IS NOT NULL
        AND GIOCIRULE IS NOT NULL;


DROP TABLE IF EXISTS TEMP_TABLE_TEST_CRIT_3;

CREATE TABLE TEMP_TABLE_TEST_CRIT_3 AS SELECT * FROM
    TEMP_TABLE_TEST
WHERE
    VEHCAT = 'BK';

DROP TABLE IF EXISTS CRIT_BK;

CREATE TABLE CRIT_BK AS SELECT NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'AAMI' AS COMPANY,
    AAMACPT AS ACCEPTCRIT,
    AAMRULE AS INTERNETJEP FROM
    TEMP_TABLE_TEST_CRIT_3
WHERE
    AAMACPT IS NOT NULL
        AND AAMRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'APIA' AS COMPANY,
    APIACPT AS ACCEPTCRIT,
    APIRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_3
WHERE
    APIACPT IS NOT NULL
        AND APIRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'SUNCORP' AS COMPANY,
    SUNACPT AS ACCEPTCRIT,
    SUNRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_3
WHERE
    SUNACPT IS NOT NULL
        AND SUNRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'GIO' AS COMPANY,
    GIOACPT AS ACCEPTCRIT,
    GIORULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_3
WHERE
    GIOACPT IS NOT NULL
        AND GIORULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'SHANNONS' AS COMPANY,
    SHNACPT AS ACCEPTCRIT,
    SHNRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_3
WHERE
    SHNACPT IS NOT NULL
        AND SHNRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'AMP' AS COMPANY,
    AMPACPT AS ACCEPTCRIT,
    AMPRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_3
WHERE
    AMPACPT IS NOT NULL
        AND AMPRULE IS NOT NULL 
UNION ALL SELECT 
    NVIC,
    VEHCAT,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    'IMR' AS COMPANY,
    IMRACPT AS ACCEPTCRIT,
    IMRRULE AS INTERNETJEP
FROM
    TEMP_TABLE_TEST_CRIT_3
WHERE
    IMRACPT IS NOT NULL
        AND IMRRULE IS NOT NULL;

DROP TABLE IF EXISTS TEMP_TABLE_TEST_CRIT_4;
CREATE TABLE TEMP_TABLE_TEST_CRIT_4 AS SELECT * FROM
    CRIT_GU 
UNION ALL SELECT 
    *
FROM
    CRIT_CI 
UNION ALL SELECT 
    *
FROM
    CRIT_BK;

DROP TABLE IF EXISTS FINAL_CRIT_EXT;
CREATE TABLE FINAL_CRIT_EXT AS SELECT NVIC,
    VEHCAT,
    COMPANY,
    EFFECTIVEDATE,
    CHANGETIMESTAMP,
    EFFECTIVEENDDATE,
    ENDDATETIMESTAMP,
    ACCEPTCRIT,
    INTERNETJEP FROM
    TEMP_TABLE_TEST_CRIT_4;


ALTER TABLE FINAL_CRIT_EXT ADD ADDMOD VARCHAR(255) FIRST;
UPDATE FINAL_CRIT_EXT 
SET 
    ADDMOD = 'ADD';

ALTER TABLE FINAL_CRIT_EXT ORDER BY VEHCAT ASC,COMPANY ASC,NVIC ASC;


DELETE FROM FINAL_CRIT_EXT WHERE NVIC LIKE '!%' AND VEHCAT = 'CI';

end;